### ISSUE TITLE
topic addition for better community reach

### ISSUE THREAD

**Issue by Wladefant** [nguillaumin/perihelion-m68k-tutorials#6]
Hey,
for better reach of the community, I would like to suggest to add the following topic to the repository: `motorola-68000`

[How to do this](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics#adding-topics-to-your-repository)

**Comment by nguillaumin** [comment]
Thanks. I already have `68000` which has 148 repositories vs. 51 for `motorola-68000`, but I guess it doesn't hurt...
